#!/usr/bin/env bash

# Functions

get() {
  curl -X GET \
    "$URL"
}

postBlog() {
  curl -X POST \
    "$blogUrl" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "title": "25 trucs",
        "author": "Tomas Laurinavicius",
        "url": "https://www.huffpost.com/entry/25-practical-blogs-to-sharpen-your-coding-skills_b_584b8011e4b01713310510cd?guccounter=1",
        "likes": 100
      }'
}

postUser() {
  curl -X POST \
    "$userUrl" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "name": "Jean",
        "username": "jean",
        "password": "truc"
      }'
}

loginUser() {
  curl -X POST \
    "$loginUrl" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "username": "gzavvo",
        "password": "truc"
      }'
}

delete() {
  curl -X DELETE \
    "$URL"
}

put() {
  curl -X PUT \
    "$URL" \
    --header 'Content-Type: application/json' \
    -d '
      {
      }'
}

# Variables

blogUrl="http://localhost:3001/api/blogs"
userUrl="http://localhost:3001/api/users"
loginUrl="http://localhost:3001/api/login"


# Samples

#get | jq
#postUser | jq
#postBlog | jq
#loginUser | jq
#delete | jq
#put | jq
