#!/usr/bin/env bash

# Functions

get() {
  curl -X GET \
    "$URL"
}

post() {
  curl -X POST \
    "$URL" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "title": "Un autre pour le fun",
        "author": "Marc Le Truc",
        "url": "http://truc",
        "likes": 134
      }'
}

delete() {
  curl -X DELETE \
    "$URL"
}

put() {
  curl -X PUT \
    "$URL" \
    --header 'Content-Type: application/json' \
    -d '
      {
      }'
}

# Variables

URL="http://localhost:3001/api/blogs"

# Samples

#get | jq
post| jq
#delete | jq
#put | jq
