#!/usr/bin/env bash

# Functions

get() {
  curl -X GET \
    "$URL"
}

post() {
  curl -X POST \
    "$URL" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "username": "gzavvo",
        "name": "Xav Bar",
        "password": "lijfes"
      }'
}

delete() {
  curl -X DELETE \
    "$URL"
}

put() {
  curl -X PUT \
    "$URL" \
    --header 'Content-Type: application/json' \
    -d '
      {
      }'
}

# Variables

URL="http://localhost:3001/api/users"

# Samples

#get | jq
post| jq
#delete | jq
#put | jq
